site :opscode

cookbook "apache2"
cookbook "database"
cookbook "mysql"
cookbook "openssl"
cookbook "php"
cookbook "owncloud", git: "git://github.com/jakobsack/owncloud-cookbook.git"
cookbook "postfix"
cookbook "owncloud-testing", git: "git://github.com/Gomez/owncloud-testing.git"
