# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  default_chef_json = {
    :mysql =>  {
      :server_root_password => "iloverandompasswordsbutthiswilldo",
      :server_repl_password => "iloverandompasswordsbutthiswilldo",
      :server_debian_password => "iloverandompasswordsbutthiswilldo"
    },
    :postgresql => {
      :password => {
        :postgres => "iloverandompasswordsbutthiswilldo"
      }
    }
  }

  # base box and URL where to get it if not present
  config.vm.box = "precise32"

  #============================================================================
  # Apache boxes
  #============================================================================
  config.vm.define "master_on_apache_with_sqlite" do |app|
    app.vm.network :hostonly, "33.33.33.10"
    app.vm.host_name = "apache01.local"
    app.vm.provision :chef_solo do |chef|
      # define our setup
      chef.json = default_chef_json.merge( {} )

      # let the recipe do all the rest
      chef.add_recipe "owncloud"
    end
  end

  config.vm.define "master_on_apache_with_mysql" do |app|
    app.vm.network :hostonly, "33.33.33.11"
    app.vm.host_name = "apache02.local"
    app.vm.provision :chef_solo do |chef|
      # define our setup
      chef.json = default_chef_json.merge( {
        :owncloud => {
          :config => {
            :dbtype => "mysql"
          }
        }
      } )

      # let the recipe do all the rest
      chef.add_recipe "owncloud"
    end
  end

  config.vm.define "master_on_apache_with_postgresql" do |app|
    app.vm.network :hostonly, "33.33.33.12"
    app.vm.host_name = "apache03.local"
    app.vm.provision :chef_solo do |chef|
      # define our setup
      chef.json = default_chef_json.merge( {
        :owncloud => {
          :config => {
            :dbtype => "pgsql"
          }
        }
      } )

      # let the recipe do all the rest
      chef.add_recipe "owncloud"
    end
  end

  #============================================================================
  # Lighttpd boxes
  #============================================================================

  #============================================================================
  # Nginx boxes
  #============================================================================
  config.vm.define "master_on_nginx_with_sqlite" do |app|
    app.vm.network :hostonly, "33.33.35.10"
    app.vm.host_name = "nginx01.local"
    app.vm.provision :chef_solo do |chef|
      # define our setup
      chef.json = default_chef_json.merge( {
        :owncloud => {
          :setup => {
            :webserver => "nginx"
          }
        }
      } )

      # let the recipe do all the rest
      chef.add_recipe "owncloud"
    end
  end

  config.vm.define "master_on_nginx_with_mysql" do |app|
    app.vm.network :hostonly, "33.33.35.11"
    app.vm.host_name = "nginx02.local"
    app.vm.provision :chef_solo do |chef|
      # define our setup
      chef.json = default_chef_json.merge( {
        :owncloud => {
          :setup => {
            :webserver => "nginx"
          },
          :config => {
            :dbtype => "mysql"
          }
        }
      } )

      # let the recipe do all the rest
      chef.add_recipe "owncloud"
    end
  end

  config.vm.define "master_on_nginx_with_postgresql" do |app|
    app.vm.network :hostonly, "33.33.35.12"
    app.vm.host_name = "nginx03.local"
    app.vm.provision :chef_solo do |chef|
      # define our setup
      chef.json = default_chef_json.merge( {
        :owncloud => {
          :setup => {
            :webserver => "nginx"
          },
          :config => {
            :dbtype => "pgsql"
          }
        }
      } )

      # let the recipe do all the rest
      chef.add_recipe "owncloud"
    end
  end
end
